[package]
name = "compiling-with-continuations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
map-macro = "0.2"
sexpr_parser = "0.3.0"
